FROM airdock/oraclejdk:latest
WORKDIR /
ADD *.jar spring-boot-microservice-eureka-naming-server-0.0.1-SNAPSHOT.jar
EXPOSE 8761
CMD java -jar spring-boot-microservice-eureka-naming-server-0.0.1-SNAPSHOT.jar

